### PR TITLE
New more "minecraftic" textures

### PR DESCRIPTION
**Pull request by jena-s-lab**
I took real life photography of the minerals from this mod then I "minecraftied" them.

Just a suggestion, use it or not, I licence that under CC0. If you don't use it I'll release it as texture pack suggested to play my modpack "Life in the Moods" since I'll use your fantastic mod :).

Enjoy.

### CODE REVIEW

**Comment by jena-th** [comment]
I'll try to add CTM informations to make larger seamless textures in the same way you tried to achieve.

**Comment by oitsjustjose** [comment]
These look great! Unfortunately, @wiiv is working on new textures. Mind if I keep these and post them on the Curse page as an alternate resource pack? You'd receive 100% credit of course!

**Comment by jena-th** [comment]
I create the resource pack on curse then I'll give you the link :) thanks

**Comment by jena-th** [comment]
https://minecraft.curseforge.com/projects/mod-ctm-minecraftic-geolosys

**Comment by jena-th** [comment]
I use GH as image plateform XD here's the latest iteration with the CTM textures.

**Pull request closed without merging**
