### PR TITLE
Fixed #269 by creating a new ore-remover implementation

### LINKED ISSUE #269: [1.16.5]Too many lakes
## Versions:
- Minecraft Forge:1.16.5-36.1.0
- Geolosys:5.1.4
- Patchouli-1.16.4-50
- 
## What happens:
(Sorry. I'm not good at English. I used Google translate.)
A huge number of lakes are generated when I use this mod. It occurs mainly in plains and forests, regardless of seed.

### PR DESCRIPTION
**Pull request by EwyBoy**
I saw your tweet and was intrigued by the issue and I figured out where the issue was in 2 minutes from looking at you're source code. I also have a ore mod named [Ore-Tweaker](https://www.curseforge.com/minecraft/mc-mods/ore-tweaker) ([Source](https://github.com/EwyBoy/OreTweaker)) that also allows users to remove ores.  

By the looks of it, **Geolosys** ends up adding way to many features back into the `BiomeGenerationSettingsBuilder` that results in  essentially creating something I would call an _"amplified biome feature world"_. It is not only the lakes that are plentiful. Pretty much all world gen features picked up by  **Geolosys** is amplified by a lot. It is just that lakes are easy to spot. The world will also contain much more Lava lakes etc.

I implemented something close to the system I am using for [Ore-Tweaker](https://github.com/EwyBoy/OreTweaker/blob/master/src/main/java/com/ewyboy/oretweaker/tweaking/construction/OreDeconstruction.java) to remove ores. It subtracts from the `BiomeGenerationSettingsBuilder` rather then adds inn and I can assure you that it is not removing to many features 😉

I kept your original code so that if you want to implement it in you're own way. The debugging has changed and moved a bit into `featureRemover()` and I tried to stay true to how the mod originally worked.

Also added [World-Stripper](https://www.curseforge.com/minecraft/mc-mods/world-stripper) ([Source](https://github.com/EwyBoy/World-Stripper)) using [CurseMaven](https://www.cursemaven.com/) to easy debug that I did not mess anything up.

Before:

After:

All ores are still gone with my ore removing implementation:

Also in nether (although you might wanna add `Magma Block` & `Blackstone` to remove list):

### CODE REVIEW

**Comment by oitsjustjose** [comment]
That makes perfect sense. I had disabled the ore removing code for debug almost immediately but didn't see any affect. I guess it was just by chance I was seeing an extra lake or two and thought "nope that didn't do it".

Thank you so much for taking the time to make this fix, I was up late last night doing so much needed refactoring which was helpful, but didn't solve the problem so I was pulling my hair out.

You are incredible :heart:

**Comment by EwyBoy** [comment]
No problem!  
I hope everything works out perfectly in the end now. Bugs like this can truly be hard to figure out.

**Comment by ghost** [comment]
Just reading through this, it's a very interesting bug with an interesting fix. Good job!

**Comment by EwyBoy** [comment]
Yes, I think the problem was due to the amount of loops in the original code:

A while loop inside a foreach loop inside a for loop causing the features to be added way to many times.
So I think each feature where being added back in as many times as there are features left in the parent loop.
```java
for (Decoration stage : Decoration.values()) {
            int start = settings.getFeatures(stage).size();
            total += start;

            settings.getFeatures(stage).forEach((supp) -> {
                ConfiguredFeature<?, ?> configuredFeature = supp.get();
                IFeatureConfig config = configuredFeature.config;

                while (config instanceof DecoratedFeatureConfig) {
                    DecoratedFeatureConfig dconfig = (DecoratedFeatureConfig) config;
                    config = dconfig.feature.get().config;
                }

                if (config instanceof OreFeatureConfig) {
                    OreFeatureConfig conf = (OreFeatureConfig) config;
                    if (!toRm.contains(conf.state.getBlock())) {
                        toKeep.add(supp);
                    }
                } else if (config instanceof ReplaceBlockConfig) {
                    ReplaceBlockConfig conf = (ReplaceBlockConfig) config;
                    if (!toRm.contains(conf.state.getBlock())) {
                        toKeep.add(supp);
                    }
                } else {
                    toKeep.add(supp);
                }
            });

            settings.getFeatures(stage).clear();
            settings.getFeatures(stage).addAll(toKeep);

            newTotal += settings.getFeatures(stage).size();
        }
```

**Pull request merged**
