### PR TITLE
Basic fix for #169

### PR DESCRIPTION
**Pull request by Vectrobe**
Seems well tuned with both AE and AA present, vanilla quartz will take either ore's place if missing.

### CODE REVIEW

**Comment by Vectrobe** [comment]
Should fix mod ore silk as well

**Comment by oitsjustjose** [comment]
Thanks a lot for this! You and I have different coding styles so I nabbed your random generator code ([credited](https://github.com/oitsjustjose/Geolosys/commit/3b249ea3e7be7eef949e5182f8a44000156a374a#diff-e466f77ff5c7506ba4c7604ff8f8588fR79)) and used it how I would probably use it. Nothing against your solution at all! Just not my style to have that big of a block in a switch statement.

**Comment by Vectrobe** [comment]
Yea, I would've suggested modularising the code more anyway, so each ore type has distinct code.

There's still Limonite, Galena, Platinum and Autunite that need correcting as well, whether you want to give them separate functions or keep it as a single switch block like I did.

**Comment by oitsjustjose** [comment]
Good point. Fixed in 572f169cc3c1a0894474896e4a3a56e610b86fc8

**Pull request closed without merging**
